apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: __IMAGE__
        ports:
        - containerPort: 5003 
        env:
        - name: DB_HOST
          value: "__DB_HOST__" 
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "__DB_PASSWORD__" 
        - name: DB_NAME
          value: banking_db