trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/frontend-service/** 

pool:
  name: 'Default'

variables:
  azureServiceConnection: 'Banking-App-Service-Connection'
  acrName: 'bankingAppRegistryDev' 
  imageName: 'frontend-service'
  tag: '$(Build.BuildId)'
  aksResourceGroup: 'Banking_Application_Dev'
  aksName: 'banking-app-aks-dev'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Frontend'
  jobs:
  - job: BuildPushJob
    steps:
    - task: AzureCLI@2
      displayName: 'Docker Build & Push'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Go to frontend source code
          cd src/frontend-service 
          
          az acr login --name $(acrName)
          docker build -t $(acrName).azurecr.io/$(imageName):$(tag) .
          docker push $(acrName).azurecr.io/$(imageName):$(tag)

- stage: DeployToAKS
  displayName: 'Deploy Frontend to AKS'
  dependsOn: BuildAndPush
  jobs:
  - job: DeployJob
    steps:
    - task: AzureCLI@2
      displayName: 'Kubectl Apply'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # 1. Inject the Build ID into the frontend manifest
          sed -i "s/__IMAGE_TAG__/$(tag)/g" kube/frontend-service.yaml
          
          # 2. Connect to AKS
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksName) --overwrite-existing

          # 3. Deploy
          kubectl apply -f kube/frontend-service.yaml