trigger: none 

pool:
  name: 'Default'

parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - qa
      - uat
      - prod
  - name: action
    displayName: 'Terraform Action'
    type: string
    default: 'plan'
    values:
      - plan
      - apply
      - destroy

# We use conditional logic to fix the redundant naming!
variables:
  - name: azureServiceConnection
    value: 'Banking-App-Service-Connection'
  - name: displayAction
    ${{ if eq(parameters.action, 'plan') }}:
      value: 'Init + Plan'
    ${{ if eq(parameters.action, 'apply') }}:
      value: 'Init + Plan + Apply'
    ${{ if eq(parameters.action, 'destroy') }}:
      value: 'Init + Plan + Destroy'

jobs:
- job: TerraformInfra
  # This will now display perfectly: "Init + Plan for dev" or "Init + Plan + Apply for qa"
  displayName: '${{ variables.displayAction }} for ${{ parameters.environment }}'
  steps:
  - task: AzureCLI@2
    displayName: 'Execute Terraform'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infrastructure
        
        
        echo " STEP 1: INITIALIZING TERRAFORM FOR ${{ parameters.environment }}"
        
        terraform init -backend-config="environments/${{ parameters.environment }}/${{ parameters.environment }}-backend.conf" -reconfigure
        
        echo " STEP 2: RUNNING TERRAFORM PLAN"
        
        if [ "${{ parameters.action }}" == "destroy" ]; then
          terraform plan -destroy -var-file="environments/${{ parameters.environment }}/${{ parameters.environment }}.tfvars"
        else
          terraform plan -var-file="environments/${{ parameters.environment }}/${{ parameters.environment }}.tfvars"
        fi
        
        echo " STEP 3: RUNNING TERRAFORM ${{ parameters.action }}"
        
        if [ "${{ parameters.action }}" == "apply" ]; then
          
          terraform apply -var-file="environments/${{ parameters.environment }}/${{ parameters.environment }}.tfvars" -auto-approve
          
        elif [ "${{ parameters.action }}" == "destroy" ]; then
          
          terraform destroy -var-file="environments/${{ parameters.environment }}/${{ parameters.environment }}.tfvars" -auto-approve
          
        elif [ "${{ parameters.action }}" == "plan" ]; then
          
          echo "Plan complete. No further action requested."
          
        fi