trigger: none 

pool:
  name: 'Default'

parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - qa
      - uat
      - prod
  - name: action
    displayName: 'Terraform Action'
    type: string
    default: 'plan'
    values:
      - plan
      - apply
      - destroy

variables:
  azureServiceConnection: 'Banking-App-Service-Connection'

jobs:
- job: TerraformInfra
  displayName: 'Init + Plan + ${{ parameters.action }} for ${{ parameters.environment }}'
  steps:
  - task: AzureCLI@2
    displayName: 'Execute Terraform'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infrastructure
        
        echo " STEP 1: INITIALIZING TERRAFORM FOR ${{ parameters.environment }}"
         
        terraform init -backend-config="environments/${{ parameters.environment }}/${{ parameters.environment }}-backend.conf" -reconfigure
         
        echo " STEP 2: RUNNING TERRAFORM PLAN"
         
        # If we are destroying, we want the plan to specifically show what will be deleted
        if [ "${{ parameters.action }}" == "destroy" ]; then
          terraform plan -destroy -var-file="environments/${{ parameters.environment }}/${{ parameters.environment }}.tfvars"
        else
          terraform plan -var-file="environments/${{ parameters.environment }}/${{ parameters.environment }}.tfvars"
        fi
        
        echo " STEP 3: RUNNING TERRAFORM ${{ parameters.action }}"
         
        if [ "${{ parameters.action }}" == "apply" ]; then
          
          terraform apply -var-file="environments/${{ parameters.environment }}/${{ parameters.environment }}.tfvars" -auto-approve
          
        elif [ "${{ parameters.action }}" == "destroy" ]; then
          
          terraform destroy -var-file="environments/${{ parameters.environment }}/${{ parameters.environment }}.tfvars" -auto-approve
          
        elif [ "${{ parameters.action }}" == "plan" ]; then
          
          echo "Plan complete. No further action requested."
          
        fi