trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/* 

parameters:
  - name: serviceName
    displayName: 'Microservice to Build'
    type: string
    default: 'user-service'
    values:
      - frontend-service
      - user-service
      - account-service
      - transaction-service
      - notification-service
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - qa
      - uat
      - prod

variables:
  acrRegistry: 'bankingappregistrydev.azurecr.io' 
  imageTag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push to ACR'
  jobs:
  - job: DockerBuild
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build & Push Docker Image'
      inputs:
        containerRegistry: '$(azureServiceConnection)' 
        repository: '$(parameters.serviceName)'
        command: 'buildAndPush'
        Dockerfile: 'src/$(parameters.serviceName)/Dockerfile'
        tags: |
          $(imageTag)
          latest

- stage: UpdateGitOps
  displayName: 'Update GitOps Manifests'
  dependsOn: BuildAndPush
  condition: succeeded()
  jobs:
  - job: CommitToGitHub
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      persistCredentials: true

    - script: |
        echo "--- 1. Updating the Tag File ---"
        TAG_FILE="kube/banking-chart/tags/${{ parameters.environment }}-${{ parameters.serviceName }}.yaml"
        
        # Overwrite the dummy file with the real Docker image tag we just built
        echo "image:" > $TAG_FILE
        echo "  tag: \"$(imageTag)\"" >> $TAG_FILE
        
        echo "--- 2. Configuring Git ---"
        git config --global user.email "kaivalya.bachkar@gmail.com"
        git config --global user.name "kaivalya-bachkar"
        
        echo "--- 3. Committing to GitHub ---"
        git add $TAG_FILE
        git commit -m "deploy: update ${{ parameters.serviceName }} to $(imageTag) in ${{ parameters.environment }} [skip ci]"
        
        echo "--- 4. Pushing to GitHub ---"
        # We use a GitHub PAT passed in as a secret variable to authenticate the push
        git push https://$(GITHUB_PAT)@github.com/kaivalya-bachkar/Banking-Application-CI-CD.git HEAD:main
      displayName: 'Commit New Tag to GitHub'
      env:
        GITHUB_PAT: $(GITHUB_PAT) 