trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/user-service/** 

pool:
  name: 'Default'

variables:
  azureServiceConnection: 'Banking-App-Service-Connection'
  acrName: 'bankingAppRegistryDev' 
  imageName: 'user-service'
  tag: '$(Build.BuildId)'
  aksResourceGroup: 'Banking_Application_Dev'
  aksName: 'banking-app-aks-dev'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push User Service'
  jobs:
  - job: BuildPushJob
    steps:
    - task: AzureCLI@2
      displayName: 'Docker Build & Push'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Go to user-service source code
          cd src/user-service
          
          az acr login --name $(acrName)
          docker build -t $(acrName).azurecr.io/$(imageName):$(tag) .
          docker push $(acrName).azurecr.io/$(imageName):$(tag)

- stage: DeployToAKS
  displayName: 'Deploy User Service to AKS'
  dependsOn: BuildAndPush
  jobs:
  - job: DeployJob
    steps:
    - task: AzureCLI@2
      displayName: 'Kubectl Apply'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # 1. Replace the Image Tag
          sed -i "s/__IMAGE_TAG__/$(tag)/g" kube/user-service.yaml
          
          # 2. Securely Inject the DB Password
          sed -i "s|__DB_PASSWORD__|$MAPPED_DB_PASS|g" kube/user-service.yaml
          
          # 3. Connect to AKS
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksName) --overwrite-existing

          # 4. Deploy
          kubectl apply -f kube/user-service.yaml
      env:
        MAPPED_DB_PASS: $(dbPassword)