trigger: none 

pool:
  name: 'Default'

parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - qa
      - uat
      - prod

variables:
  - name: azureServiceConnection
    value: 'Banking-App-Service-Connection'
  - name: imageName
    value: 'user-service'
  - name: tag
    value: '$(Build.BuildId)'
  
  - ${{ if eq(parameters.environment, 'dev') }}:
    - name: acrName
      value: 'bankingappregistrydev'
    - name: aksResourceGroup
      value: 'Banking_Application_Dev'
    - name: aksName
      value: 'banking-app-aks-dev'
    - name: dbHost
      value: 'bankingdev-psqlflexibleserver.postgres.database.azure.com'
      
  - ${{ if eq(parameters.environment, 'qa') }}:
    - name: acrName
      value: 'bankingAppRegistryQA'
    - name: aksResourceGroup
      value: 'Banking_Application_QA'
    - name: aksName
      value: 'banking-app-aks-qa'
    - name: dbHost
      value: 'bankingqa-psqlflexibleserver.postgres.database.azure.com'

  - ${{ if eq(parameters.environment, 'uat') }}:
    - name: acrName
      value: 'bankingAppRegistryUAT'
    - name: aksResourceGroup
      value: 'Banking_Application_UAT'
    - name: aksName
      value: 'banking-app-aks-uat'
    - name: dbHost
      value: 'bankinguat-psqlflexibleserver.postgres.database.azure.com'

  - ${{ if eq(parameters.environment, 'prod') }}:
    - name: acrName
      value: 'bankingAppRegistryProd'
    - name: aksResourceGroup
      value: 'Banking_Application_Prod'
    - name: aksName
      value: 'banking-app-aks-prod'
    - name: dbHost
      value: 'bankingprod-psqlflexibleserver.postgres.database.azure.com'

stages:
- stage: BuildAndDeploy
  displayName: 'Deploy User Service to ${{ parameters.environment }}'
  jobs:
  - job: BuildPushDeploy
    steps:
    - task: AzureCLI@2
      displayName: 'Build, Push, and Deploy'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -e 
          echo " TARGET ENVIRONMENT: ${{ parameters.environment }}"
          echo " DB HOST: $(dbHost)"
          
          cd src/user-service
          
          echo "--- 1. Building Image for ${{ parameters.environment }} ---"
          az acr login --name $(acrName)
          docker build -t $(acrName).azurecr.io/$(imageName):$(tag) .
          docker push $(acrName).azurecr.io/$(imageName):$(tag)
          
          echo "--- 2. Routing the Secret DB Password ---"
          CURRENT_DB_PASS=""
          if [ "${{ parameters.environment }}" == "dev" ]; then
            CURRENT_DB_PASS=$DB_PASS_DEV
          elif [ "${{ parameters.environment }}" == "qa" ]; then
            CURRENT_DB_PASS=$DB_PASS_QA
          elif [ "${{ parameters.environment }}" == "uat" ]; then
            CURRENT_DB_PASS=$DB_PASS_UAT
          elif [ "${{ parameters.environment }}" == "prod" ]; then
            CURRENT_DB_PASS=$DB_PASS_PROD
          fi
          
          echo "--- 3. Injecting Variables into Manifest ---"
          cd ../../ 
          sed -i "s/__IMAGE_TAG__/$(tag)/g" kube/user-service.yaml
          sed -i "s|bankingAppRegistryDev.azurecr.io|$(acrName).azurecr.io|g" kube/user-service.yaml
          sed -i "s/__DB_HOST__/$(dbHost)/g" kube/user-service.yaml
          
          sed -i "s|__DB_PASSWORD__|$CURRENT_DB_PASS|g" kube/user-service.yaml
          
          eecho "--- 4. Deploying to $(aksName) via AKS Run Command ---"
          az aks command invoke \
            --resource-group $(aksResourceGroup) \
            --name $(aksName) \
            --command "kubectl apply -f user-service.yaml" \
            --file kube/user-service.yaml
      
      env:
        DB_PASS_DEV: $(dbPasswordDev)
        DB_PASS_QA: $(dbPasswordQA)
        DB_PASS_UAT: $(dbPasswordUAT)
        DB_PASS_PROD: $(dbPasswordProd)